language: node_js

sudo: false
dist: trusty

node_js:
  - '8'
  - '9'
  - '10'

branches:
  only:
  - master
  - starter-kit
  - demo

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - npm i -g npm@latest

install:
  - travis_retry npm i

before_script:

script:
  - npm run lint:ci
  - npm run build:prod

git:
  depth: 1

deploy:
  provider: heroku
  api_key:
    secure: 283b0a80-79b0-4551-9422-f80aef94d10b
    app: pagandopouco
  on:
    repo: magnocarvalho/adm-tcc
  skip_cleanup: true